# Generated by Django 4.2.1 on 2023-06-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, null=True)),
                ('token', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
    ]
